trigger:
- master

pool:
  name: windows-latest

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  webAppName: 'fiapcloudgames-hmg'

stages:
- stage: Build
  displayName: Build and Publish
  jobs:
  - job: Build
    pool:
      name: Default
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'

- stage: DeployHMG
  displayName: Deploy to Azure Web App (HMG)
  dependsOn: Build
  jobs:
  - deployment: DeployWebHMG
    pool:
      name: Default
    environment: HMG
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: '$(artifactName)'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'sc-fiapcloudgames'
              appType: 'webApp'
              appName: '$(webAppName)'
              package: '$(System.ArtifactsDirectory)/$(artifactName)/**/*.zip'
