trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrLoginServer: 'fcregistry.azurecr.io'
  imageRepository: 'fiapcloudgames'
  containerTag: '$(Build.BuildId)'
  azureSubscription: 'sc-fiapcloudgames'
  webAppName: 'fiapcloudgames-app'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Docker
    displayName: Build and Push
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: '$(acrLoginServer)'

    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        repository: $(imageRepository)
        Dockerfile: '**/Dockerfile'
        tags: |
          $(containerTag)
          latest

    - task: Docker@2
      displayName: Push Image
      inputs:
        command: push
        repository: $(imageRepository)
        tags: |
          $(containerTag)
          latest

- stage: Deploy
  displayName: Deploy to App Service
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployToAppService
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to Web App for Containers
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              containers: |
                $(acrLoginServer)/$(imageRepository):$(containerTag)
